/*********************************************
**	        	 Rakshata v1.1 		        **
**     Licence propriétaire, code source    **
**        confidentiel, distribution        **
**          formellement interdite          **
**********************************************/

/*DEFINES*/

/*Général*/
#define LARGEUR 800 //Largeur par défaut
#define HAUTEUR_INTERDIT_WHILE_DL 400
#define HAUTEUR_MAX_LEGALE 1000
#define LARGEUR_MAX 1260
#define BARRE_DES_TACHES_WINDOWS 75
#define PERMISSIONS 0755
#define NOMBRE_TEAM_MAX 100
#define TAILLE_BUFFER 100
#define MAX_INT 2147483646
#define NEW_FONT

/*Thread*/
#ifdef _WIN32
    #define quit_thread(a) ExitThread(a)
#else
    #define quit_thread(a) pthread_exit(a)
#endif


/*Environnement*/
#define MANGA_DATABASE "data/mangas"
#define FONT_USED_BY_DEFAULT "data/font.ttf"

#ifdef DEV_VERSION
    #define BUILD "dev"
#else
    #ifdef _WIN32
        #define BUILD "win32"
    #else
        #ifdef __APPLE__
            #define BUILD "OSX"
        #else
            #define BUILD "linux"
        #endif
    #endif
#endif


/*Standard des dépôts*/
#define CONFIGFILE "config.dat"
#define VERSION_REPO 1
#define VERSION_MANGA 1

/*Réseau*/
#define CONNEXION_TEST_IN_PROGRESS -1
#define CONNEXION_OK 0
#define CONNEXION_SERVEUR_DOWN 1
#define CONNEXION_DOWN 2

/*Structure principale -> paliers*/
#define PALIER_DEFAULT -1
#define PALIER_CHAPTER -2
#define PALIER_MENU -3
#define PALIER_QUIT -4

/*Langue*/
#define NOMBRE_LANGUE 4
#define LANGUE_PAR_DEFAUT 1
#define LARGEUR_LANGUE 800
#define HAUTEUR_LANGUE 400
#define HAUTEUR_MENU_LANGUE 30
#define HAUTEUR_TEXTE_LANGUE 100
#define INTERLIGNE_LANGUE 10

/*Police*/
#define POLICE_TOUT_PETIT 16
#define POLICE_PETIT 18
#define POLICE_MOYEN 22
#define POLICE_GROS 26

/*Couleurs*/
#define POLICE_R 0
#define POLICE_G 0
#define POLICE_B 0
#define POLICE_NEW_R 255
#define POLICE_NEW_G 47
#define POLICE_NEW_B 47
#define POLICE_UNREAD_R 48
#define POLICE_UNREAD_G 170
#define POLICE_UNREAD_B 0
#define POLICE_ENABLE_R 255
#define POLICE_ENABLE_G 47
#define POLICE_ENABLE_B 47
#define POLICE_UNAVAILABLE_R 77 //Ou 102
#define POLICE_UNAVAILABLE_G 77
#define POLICE_UNAVAILABLE_B 77
#define FOND_R 214
#define FOND_G 214
#define FOND_B 214

/*Section*/
#define NOMBRESECTION 4
#define SECTION_CHOISIS_LECTURE 1
#define SECTION_DL 2
#define SECTION_CHOISIS_TEAM 5
#ifdef NEW_FONT
	#define BORDURE_SUP_MENU 30
	#define INTERLIGNE_MENU 15
	#define BORDURE_SUP_SECTION 100
	#define INTERLIGNE_SECTION 10
#else
	#define BORDURE_SUP_MENU 50
	#define INTERLIGNE_MENU 20
	#define BORDURE_SUP_SECTION 150
	#define INTERLIGNE_SECTION 25
#endif
#define BORDURE_VERTICALE_SECTION 75
#define HAUTEUR_FENETRE_SECTION 500

/*Selection manga*/
#ifdef NEW_FONT
	#define BORDURE_SUP_TITRE_MANGA 15
	#define LARGEUR_MOYENNE_MANGA_PETIT 30
	#define LARGEUR_MOYENNE_MANGA_MOYEN 36
	#define LARGEUR_MOYENNE_MANGA_GROS 43
	#define INTERLIGNE 20
	#define MINIINTERLIGNE 5
#else
	#define BORDURE_SUP_TITRE_MANGA 30
	#define LARGEUR_MOYENNE_MANGA_PETIT 19
	#define LARGEUR_MOYENNE_MANGA_MOYEN 23
	#define LARGEUR_MOYENNE_MANGA_GROS 27
	#define INTERLIGNE 35
	#define MINIINTERLIGNE 15
#endif
#define BORDURE_SUP_SELEC_MANGA 140
#define BORDURE_SUP_SELEC_MANGA_LECTURE 160
#define MANGAPARPAGE_DUO 14
#define MANGAPARPAGE_TRI 30
#define NBRCOLONNES_DUO 2
#define NBRCOLONNES_TRI 3
#define LONGUEURTEXTE 100
#define LONGUEURMANGA 200
#define BORDURELATSELECTION 45
#define HAUTEURNUMEROTATION_OLD 50
#define HAUTEURNUMEROTATION_NEW 50
#define BANDEAU_INF_NEW 20
#define BORDURE_INF_NUMEROTATION_TRI 70
#define HAUTEUR_BOUTONS_DL 575
#define NOMBRE_LETTRE_MAX 20

/*Multi Page*/
#define HAUTEUR_BOUTONS_CHANGEMENT_PAGE 105
#define LONGUEUR_PRECENDENT 169
#define LONGUEUR_SUIVANT 141

/*Bandeau de contrôle*/
#define LARGEUR_BANDEAU_CONTROLE_SELECTION_MANGA 140
#define HAUTEUR_PREMIERE_LIGNE_BANDEAU_CONTROLE 50
#define LARGEUR_INTERLIGNE_BANDEAU_CONTROLE 30
#define COORDONEE_X_PREMIERE_COLONNE_BANDEAU_CONTROLE 50
#define COORDONEE_X_DEUXIEME_COLONNE_BANDEAU_CONTROLE 310
#define COORDONEE_X_TROISIEME_COLONNE_BANDEAU_CONTROLE 570
#define LARGEUR_MOYENNE_BOUTON_RESTRICTION 175

/*Chapitre*/
#define NOMBRE_CHAPITRE_MAX 300
#define BORDURE_SUP_TITRE_CHAPITRE 20
#define BORDURE_SUP_INFOS_MANGA 150
#define BORDURE_SUP_CHAPITRE 225
#define BORDURE_SUP_NUMEROTATION_CHAPITRE 450
#define BORDURE_SUP_INFOS_TEAM_CHAPITRE 60
#define HAUTEUR_BOUTONS_CHAPITRE 40
#define BORDURE_BOUTON_LECTEUR 20
#define SEPARATION_COLONNE_1_CHAPITRE 220
#define SEPARATION_COLONNE_2_CHAPITRE 570
#define CODE_CLIC_LIEN_CHAPITRE 13371337
#define CODE_BOUTON_1_CHAPITRE 13371338
#define CODE_BOUTON_2_CHAPITRE 13371339
#define CODE_BOUTON_3_CHAPITRE 13371340
#define SECTION_CHOISIS_CHAPITRE 7

/**Lecteur**/

    /*Mouvements*/
    #define DEPLACEMENT 50
    #define DEPLACEMENT_SOURIS 7
    #define DEPLACEMENT_LATERAL_PAGE 5
    #define DEPLACEMENT_HORIZONTAL_PAGE 5
    #define TOLERANCE_CLIC_PAGE 10

    /*Limites buffers*/
    #define NOMBRE_PAGE_MAX 500
    #define LONGUEUR_NOM_PAGE 100

    /*Tailles*/
    #define BORDURE_LAT_LECTURE 20
    #define BORDURE_HOR_LECTURE 40
    #define BORDURE_INFERIEURE 25
    #define BORDURE_BUTTON_H 5
    #define BORDURE_BUTTON_W 10
    #define BORDURE_CONTROLE_LECTEUR 100
    #define LARGEUR_CONTROLE_LECTEUR 800
    #define MINIICONE_H 42
    #define MINIICONE_W 42
    #define BIGICONE_H 95
    #define BIGICONE_W 95

    /*Positions*/
    #define LARGE_BUTTONS_LECTEUR_PC 30
    #define LARGE_BUTTONS_LECTEUR_PP 185
    #define LARGE_BUTTONS_LECTEUR_NP 510
    #define LARGE_BUTTONS_LECTEUR_NC 665

    /*Return values*/
    #define CLIC_SUR_BANDEAU_NONE 0
    #define CLIC_SUR_BANDEAU_PREV_CHAPTER 1
    #define CLIC_SUR_BANDEAU_PREV_PAGE 2
    #define CLIC_SUR_BANDEAU_NEXT_PAGE 3
    #define CLIC_SUR_BANDEAU_NEXT_CHAPTER 4
    #define CLIC_SUR_BANDEAU_FAVORITE 5
    #define CLIC_SUR_BANDEAU_FULLSCREEN 6
    #define CLIC_SUR_BANDEAU_DELETE 7
    #define CLIC_SUR_BANDEAU_MAINMENU 8

    /*Calibration*/
    #define LECTEUR_DISTANCE_OPTIMALE_INFOS_ET_PAGEACCESDIRE 100
    #define LECTEUR_DISTANCE_MINIMALE_INFOS_ET_PAGEACCESDIRE 5
    #define DELAY_KEY_PRESSED_TO_START_PAGE_SLIDE 350

/*UIAlert*/
#define INTERLIGNE_UIALERT 5
#define BORDURE_SUP_UIALERT 10
#define LARGEUR_UIALERT 250
#define HAUTEUR_EXPLICATION 110
#ifdef NEW_FONT
    #define EPAISSEUR_LIGNE_MOYENNE 30
#else
    #define EPAISSEUR_LIGNE_MOYENNE 19
#endif

/*Mangas*/
#define NOMBRE_MANGA_MAX 5000//8395
#define NOMBRE_MANGA_MAX_PAR_DEPOT 1000
#define LONGUEUR_NOM_MANGA_MAX 50
#define LONGUEUR_COURT 10
#define LONGUEUR_SITE 100

/*Check environnement*/
#define NOMBRE_DE_FICHIER_A_CHECKER 22
#define LONGUEUR_NOMS_DATA 100

/*Show numéro*/
#define HAUTEUR_BORDURE_AFFICHAGE_NUMERO 30

/*Module Gestion*/
#define NOMBRE_MENU_GESTION 3
#define HAUTEUR_TEXTE 30
#ifdef NEW_FONT
    #define HAUTEUR_CHOIX 75
#else
    #define HAUTEUR_CHOIX 100
#endif
#define NOMBRE_MENU 5
#define HAUTEUR_SELECTION_REPO 350

/*Ajout repo*/
#define BUFFER_MAX 100
#define HAUTEUR_MENU_AJOUT_REPO 50
#define HAUTEUR_FENETRE_AJOUT_REPO_INIT 200
#define HAUTEUR_FENETRE_AJOUT_REPO 250
#define HAUTEUR_ID_AJOUT_REPO 150
#define HAUTEUR_TEAM_AJOUT_REPO 175
#define LONGUEUR_ID_MAX 6
#define TYPE_DEPOT_1 "DB" //Dépôt dropbox
#define TYPE_DEPOT_2 "O" //Dépôt classique
#define TYPE_DEPOT_3 "P" //Dépôts payants
#define TYPE_DEPOT_4 "GOO" //Raccourcis pour acceder au dépôt


/*Suppression repo*/
#define HAUTEUR_DEL_REPO 275
#define HAUTEUR_MENU_CONFIRMATION_SUPPRESSION 50
#define HAUTEUR_TEAM_CONFIRMATION_SUPPRESSION 125
#define HAUTEUR_CONSIGNES_CONFIRMATION_SUPPRESSION 200
#define HAUTEUR_LISTE 100

/*Module update*/
#define HAUTEUR_MESSAGE_INITIALISATION 50
#define HAUTEUR_TEXTE_TELECHARGEMENT 125
#define HAUTEUR_POURCENTAGE 200
#ifdef NEW_FONT
	#define BORDURE_POURCENTAGE 140
#else
	#define BORDURE_POURCENTAGE 100
#endif
#define HAUTEUR_FENETRE_DL 250
#define HAUTEUR_AFFICHAGE_INITIALISATION 75
#define LONGUEUR_URL 300

/*Mise Ã  jour*/
#define HAUTEUR_MAJ 250

/*Download.c*/
#define MODE_DOWNLOAD_VERBOSE_ENABLE 1

/*Database*/
#define SIZE_BUFFER_UPDATE_DATABASE 100000
#define NUMBER_MAX_TEAM_KILLSWITCHE 200

/*Sécurité*/
#define EVERYTHING_IN_HDD 1
#define INPUT_IN_MEMORY 2
#define OUTPUT_IN_MEMORY 3
#define EVERYTHING_IN_MEMORY 4
#define OUTPUT_IN_HDD_BUT_INCREMENTAL 5
#define MODE_RAK 6
#define NOMBRE_CLE_MAX_ACCEPTE 10
#define FULL_ENCRYPTION 1
#define FAKE_PASSWORD "LeS3ul3tUn1queBu7D3C3M0tD3P4ss3457D3F41r3[|-|13rL3sK1k00s"
#define MESSAGE_PASSWORD "0x4b4d1d341N33d4Password4b4d1d34"

/*Hash algorithms*/
#define SHA256_BLOCK_LENGTH	64
#define SHA256_DIGEST_LENGTH 32
#define HASH_LENGTH 65
#define PBKDF2_OUTPUT_LENGTH 32

/*Login*/
#define SIZE_WINDOWS_AUTHENTIFICATION 250

/*Trad*/
#define NOMBRE_TRAD_ID_MAX 28
#define SIZE_TRAD_ID_1 7
#define SIZE_TRAD_ID_2 6
#define SIZE_TRAD_ID_3 7
#define SIZE_TRAD_ID_4 2
#define SIZE_TRAD_ID_5 1
#define SIZE_TRAD_ID_6 2
#define SIZE_TRAD_ID_7 2
#define SIZE_TRAD_ID_8 2
#define SIZE_TRAD_ID_9 2
#define SIZE_TRAD_ID_10 2
#define SIZE_TRAD_ID_11 14
#define SIZE_TRAD_ID_12 4
#define SIZE_TRAD_ID_13 10
#define SIZE_TRAD_ID_14 4
#define SIZE_TRAD_ID_15 1
#define SIZE_TRAD_ID_16 6
#define SIZE_TRAD_ID_17 7
#define SIZE_TRAD_ID_18 3
#define SIZE_TRAD_ID_19 14
#define SIZE_TRAD_ID_20 6
#define SIZE_TRAD_ID_21 20
#define SIZE_TRAD_ID_22 6
#define SIZE_TRAD_ID_23 2
#define SIZE_TRAD_ID_24 2
#define SIZE_TRAD_ID_25 2
#define SIZE_TRAD_ID_26 16
#define SIZE_TRAD_ID_27 4
#define SIZE_TRAD_ID_28 2
